import { useMemo, useState } from 'react';
import { Alert, Button, Card, Form, Select, Table, Tag, message } from 'antd';
import { UserAddOutlined } from '@ant-design/icons';
import { callFetchMyAssignedLeads } from '@/config/api';
import { ConsultantEmpty, ConsultantState, useConsultantData } from './consultant.shared';
import styles from '@/styles/client.module.scss';

const ConsultantEnrollments = () => {
    const data = useConsultantData(); const [leadId, setLeadId] = useState(''); const [courseId, setCourseId] = useState(''); const [classId, setClassId] = useState('');
    const classes = useMemo(() => data.classrooms.filter(item => item.course_id?._id === courseId && item.status === 'OPEN'), [courseId, data.classrooms]);
    return <main className={`${styles.container} ${styles['consultant-page']}`}><section className={styles['consultant-page-heading']}><div><span>CONSULTANT / ENROLLMENTS</span><h1>Đăng ký học</h1><p>Chuẩn bị thông tin đăng ký cho khách hàng quan tâm.</p></div></section><Alert className={styles['consultant-alert']} type="info" showIcon message="Lead chưa có tài khoản Student" description="Backend hiện yêu cầu student_id là User hợp lệ. Không thể tự gán lead_id thành student_id; cần quy trình chuyển Lead thành Student trước khi tạo Enrollment." /><ConsultantState loading={data.loading} error={data.error}>{!data.leads.length ? <ConsultantEmpty description="Chưa có khách hàng để đăng ký" /> : <Card className={styles['portal-card']} title={<><UserAddOutlined /> Chọn thông tin đăng ký</>}><Form layout="vertical"><Form.Item label="Khách hàng"><Select showSearch optionFilterProp="label" value={leadId || undefined} onChange={setLeadId} options={data.leads.map(lead => ({ label: `${lead.full_name || lead.name} · ${lead.email}`, value: lead._id || '' })).filter(option => option.value)} /></Form.Item><Form.Item label="Khóa học"><Select showSearch optionFilterProp="label" value={courseId || undefined} onChange={value => { setCourseId(value); setClassId(''); }} options={data.courses.map(course => ({ label: `${course.name} · ${course.level || ''}`, value: course._id || '' })).filter(option => option.value)} /></Form.Item><Form.Item label="Lớp học phù hợp"><Select value={classId || undefined} onChange={setClassId} disabled={!courseId} placeholder="Chọn lớp đang mở" options={classes.map(item => ({ label: `${item.class_name} · ${item.room || 'Chưa có phòng'} · ${item.start_time || ''}-${item.end_time || ''}`, value: item._id || '' })).filter(option => option.value)} /></Form.Item><Button type="primary" disabled={!leadId || !courseId || !classId} onClick={() => message.info('Chưa thể tạo Enrollment: backend chưa có API chuyển Lead thành Student.')}>Xác nhận đăng ký</Button></Form></Card>}</ConsultantState></main>;
};
export default ConsultantEnrollments;
