import { useMemo, useState } from 'react';
import { Button, Card, Input, Modal, Select, Table, Tag } from 'antd';
import { BookOutlined, EyeOutlined } from '@ant-design/icons';
import { ConsultantEmpty, ConsultantState, money, useConsultantData } from './consultant.shared';
import type { ICourse } from '@/types/backend';
import styles from '@/styles/client.module.scss';

const ConsultantCourses = () => {
    const data = useConsultantData();
    const [search, setSearch] = useState(''); const [level, setLevel] = useState<string>(); const [selected, setSelected] = useState<ICourse | null>(null);
    const courses = useMemo(() => data.courses.filter(course => `${course.name} ${course.description}`.toLowerCase().includes(search.toLowerCase()) && (!level || course.level === level)), [data.courses, level, search]);
    return <main className={`${styles.container} ${styles['consultant-page']}`}><section className={styles['consultant-page-heading']}><div><span>CONSULTANT / COURSES</span><h1>Kho khóa học tư vấn</h1><p>Cung cấp thông tin chương trình học phù hợp cho từng khách hàng.</p></div></section><ConsultantState loading={data.loading} error={data.error}>{!data.courses.length ? <ConsultantEmpty description="Chưa có khóa học" /> : <Card className={styles['portal-card']}><div className={styles['consultant-filters']}><Input.Search placeholder="Tìm tên khóa học" value={search} onChange={event => setSearch(event.target.value)} /><Select allowClear placeholder="Cấp độ" value={level} onChange={setLevel} options={[...new Set(data.courses.map(course => course.level).filter(Boolean))].map(value => ({ label: value, value }))} /></div><Table rowKey="_id" dataSource={courses} pagination={{ pageSize: 8 }} scroll={{ x: 850 }} columns={[{ title: 'Khóa học', render: (_: unknown, course) => <span className={styles['consultant-person']}><BookOutlined /> {course.name}</span> }, { title: 'Mô tả', dataIndex: 'description', ellipsis: true }, { title: 'Cấp độ', dataIndex: 'level' }, { title: 'Thời lượng', dataIndex: 'duration' }, { title: 'Học phí', render: (_: unknown, course) => money(course.price) }, { title: 'Trạng thái', render: (_: unknown, course) => <Tag color={course.status === 'ACTIVE' ? 'green' : 'gold'}>{course.status || 'Đang mở'}</Tag> }, { title: 'Xem', render: (_: unknown, course) => <Button icon={<EyeOutlined />} onClick={() => setSelected(course)}>Chi tiết</Button> }]} /></Card>}</ConsultantState><Modal title={selected?.name} open={Boolean(selected)} footer={null} onCancel={() => setSelected(null)}><div className={styles['consultant-course-detail']}><h3>{selected?.name}</h3><p>{selected?.description || 'Chưa có mô tả.'}</p><div><b>Cấp độ:</b> {selected?.level || 'Mọi trình độ'}</div><div><b>Thời lượng:</b> {selected?.duration || 'Linh hoạt'}</div><div><b>Học phí:</b> {money(selected?.price)}</div><h4>Lớp đang mở</h4>{data.classrooms.filter(item => item.course_id?._id === selected?._id && item.status === 'OPEN').map(item => <p key={item._id}>{item.class_name} · {item.room} · {item.start_time} - {item.end_time}</p>)}</div></Modal></main>;
};
export default ConsultantCourses;
